# apimatic_calculator
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module ApimaticCalculator
  # HTTP Methods Enumeration.
  class HttpMethodEnum < CoreLibrary::HttpMethod
  end
end
